apiVersion: v1
kind: Service
metadata:
  namespace: 'exam-4kub'
  name: prestashop-service
spec:
  type: NodePort
  selector:
    app: prestashop
  ports:
    - port: 8080
      nodePort: 30000
      name: http

